### ISSUE TITLE
Different spreadsheet view

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#193] opened 2017-06-03 11:35 UTC
The current spreadsheet view has a number of issues that mean it isn't useable for the workflow intended, and unfortunately I think this may need some work.

This view has a lag, presumably due to large amount of data required so does not update in good time for vehicle changes.  This is what eventually resulted in large numbers of event, vehicle requests etc all on the same day.  Would it be better if, rather than dropdowns etc, each cell was a link to a popup to complete the input for that cell Kind of like the main month page, but retaining the wider view with all the detail displayed. This view would be accessible to everyone, but only editable by the appropriate roles - riders would be able to claim their duty slots here, but only the rota manager would assign the vehicles. In this way, only the data for the cell need be transfered back and forth with each edit? It might also make sense to "lock" a slot data so that two people can't try to claim the slot at the same time - in effect if a slot is locked, the link isn't a link. The thought was something similar to booking theatre seats - you click the seat (slot) and you then have a minute or so to pay up (claim the slot) or it times out and the lock is released.  I'm not sure how the view on another machine would be refreshed to reflect any edits - some kind of "push" notification ideally I guess, but I've no clue how to implement that here.
It might be worth considering the possibility of a "submit" button, allowing a number of edits to be made locally, then committing everything back in one hit so that you could, for instance, allocate vehicles to a number of slots, change your mind a few times then commit when happy, or claiming friday, saturday, sunday slots, noticing you picked the wrong weekend, change your selection then commit?

The table itself should include both controllers and event allocations as well as duty shifts, but we could have a way of hiding things not of interest; perhaps check boxes that allow showing/hiding Controller, Rider, Driver or Events rows. 

![screen shot 2017-06-03 at 12 04 29](https://cloud.githubusercontent.com/assets/16360425/26753016/fffa63b2-4854-11e7-9e1a-ad68bbb7ee94.png)

Each "cell" would be a hyperlink to a a popup to "claim slot" or "assign vehicle" etc as appropriate in a similar fashion to the current day view. In effect, there would be rows of seven "day view" blocks, with up to N events listed at the top (we should restrict to N (4 I think) events allowable per day).  Where there is a dropdown to select a vehicle in this popup, it would be very useful if inappropriate choices could be removed (vehicles already allocated on that day for instance)

We must disallow claiming a day-time duty slot for non-bank holidays to prevent people cocking it it up - and they will. One option for implementing this would be to always disallow weekday daytime slots, with a database table of bank-holiday "overrides" which would thus re-enable certain days. This table could be manually populated, probably once a year if that, as the dates are published.

The table needs to be scaleable such that all 7 days of one week are visible across the screen, changing the font size and/or column widths if necessary whilst remaining readable.  It is therefore unlikely that a mobile version would ever be able to accommodate a week view without scrolling, so having to scroll in a mobile view is okay.

The vehicle allocator needs to be able to see at-a-glance the vehicle and riders across at least two weeks, ideally four, to be able plan not just the next vehicle allocation/movement but how that relates to allocations a week or two ahead.

When a rider is choosing hist duties, they often need to see who is doing the duties around them so that they can judge how far they might have to travel to collect the bike they would be using. Given that our area is nearly 2500 square miles, the distances can be quite large even within a N/C/S area.

**Comment by pjfl** [comment] 2017-06-03 16:46
"This view has a lag, presumably due to large amount of data required so does not update in good time for vehicle changes". Would dispute that

**Comment by pjfl** [comment] 2017-06-03 16:47
"this is what eventually resulted in large numbers of event, vehicle requests etc all on the same day" and that's going to need explaining

**Comment by pjfl** [comment] 2017-06-03 16:50
"Would it be better if, rather than dropdowns etc, each cell was a link to a popup to complete the input for that cell Kind of like the main month page, but retaining the wider view with all the detail displayed. " so no difference other than a dialog with a select list and a button, rather than a select list with an onchange submit handler. I see no point in doing that

**Comment by pjfl** [comment] 2017-06-03 16:53
"This view would be accessible to everyone, but only editable by the appropriate roles - riders would be able to claim their duty slots here, but only the rota manager would assign the vehicles." This a heavyweight page and it's only set to get heavier. You want to direct general traffic to it rather than the much lighter existing page, makes no sense. Yes this page is just for Guy

**Comment by pjfl** [comment] 2017-06-03 16:54
"In this way, only the data for the cell need be transfered back and forth with each edit?" That not how a web app works, so no

**Comment by pjfl** [comment] 2017-06-03 16:56
"It might also make sense to "lock" a slot data so that two people can't try to claim the slot at the same time - in effect if a slot is locked, the link isn't a link. ". No it make no sense to "lock a slot", when would the "lock" start, end, what.... long list of wtf questions, so no locks

**Comment by pjfl** [comment] 2017-06-03 16:59
"The thought was something similar to booking theatre seats - you click the seat (slot) and you then have a minute or so to pay up (claim the slot) or it times out and the lock is released. I'm not sure how the view on another machine would be refreshed to reflect any edits - some kind of "push" notification ideally I guess, but I've no clue how to implement that here". This is not going to happen so you need to start rethinking this ticket

**Comment by pjfl** [comment] 2017-06-03 17:02
"It might be worth considering the possibility of a "submit" button, allowing a number of edits to be made locally, then committing everything back in one hit so that you could, for instance, allocate vehicles to a number of slots, change your mind a few times then commit when happy, or claiming friday, saturday, sunday slots, noticing you picked the wrong weekend, change your selection then commit?"

Now your just making shit up, what happened to "the workflow intended" what then is the intended workflow? Again no two phase commit in this app and Guy isn't going to accept it anyway

**Comment by pjfl** [comment] 2017-06-03 17:06
"The table itself should include both controllers and event allocations as well as duty shifts, but we could have a way of hiding things not of interest; perhaps check boxes that allow showing/hiding Controller, Rider, Driver or Events rows." That stuff is already on the existing view in the mouse overs. There's no space so more shit won't fit. So either the extra data get shipped with page load making everything so much heavier or it's loading async and this would just be replacing the mouse overs with so click to show/hide panel containing the same information

**Comment by pjfl** [comment] 2017-06-03 17:07
Giving up on the rest of this

**Comment by JB62** [comment] 2017-06-03 17:15
He's actually very keen to get it to work, but it does have to work in a way that supports what he (or anyone else does), and it does have to be robust against idiot users. I spent over three hours with him and another chap that would be doing this, where they explained what goes on, and to do what they do with it as it stands would take many times longer than with the current creaky spreadsheet. This is entirely my fault for not getting the requirements accurately in the first place, but that's too late now. This is exactly why I said we need to go over it.

**Comment by JB62** [comment] 2017-06-03 19:00
I think part of the problem with the current view is that when you allocate a vehicle, the whole page gets redrawn, when it's only really necessary to update a small area. This at least gives the perception of lots of lag. Rather than refreshing the whole page when the dropdown closes, would it be feasible to fire off a request for data ( JQuery?? ) such that javascript can update just the affected elements?

**Comment by JB62** [comment] 2017-06-03 23:31
This is how Guy describes creating the great list of event allocations on 25th May (and 2nd June)...

"I created several events first and requested a number of vehicles for each then set about trying to assign vehicles in the spreadsheet view. Each time I allocated a bike I clicked the next button then the previous button to see if the allocation had taken. In each case they did not. The only way I could get a bike to allocate was to go back to the individual event and assign a bike. However after doing that I returned to the spreadsheet view and the bike was still not assigned. Moving on to test other elements I then returned later to the spreadsheet view to find it as you see it now."

So I'm now suspecting that particular problem might be more to do with the next/prev buttons and browser caching, but I'm not sure.

**Comment by pjfl** [comment] 2017-06-04 16:31
Does he even have javascript enabled? It sounds like he doesn't. Each time he allocated a bike it redrew the screen and showed him that the bike had been allocated. The prev and next buttons dont't come into it, but they can easily be removed if they are too complicated for him. Bikes are either assigned (a notification appears in the bottom right hand corner) or not there is no lag or catching up

Since you've opened another ticket on this subject I'm closing this one as invalid

**Closed by pjfl** 2017-06-04 16:31 UTC
Labels: invalid

**Comment by JB62** [comment] 2017-06-04 16:35
I don't know whether js was enabled, but I imagine it was. Either way, perhaps check for it being enabled an a (polite) sod off message if it isn't?



-----Original Message-----

**Comment by pjfl** [comment] 2017-06-04 17:55
As it turns out without js enabled you cannot see the spreadsheet view.

I've checked out the screen for June 2 on your uat site and it's functioning as intended. Vehicles can be assigned and unassigned just fine. Collision detection is working and there is not perceptable lag, just a page reload with the onchange submit. The only issue is that because Guy is using unrealistic make up data test test2 test2a test2b when you try to assign edith for the third time it says not its already assigned to a very similarly named event
