### ISSUE TITLE
Can't delete an event

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#22] opened 2016-04-03 09:30 UTC
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Cannot delete or update a parent row: a foreign key constraint fails (`schedule`.`vehicle_request`, CONSTRAINT `vehicle_request_fk_event_id` FOREIGN KEY (`event_id`) REFERENCES `event` (`id`)) [for Statement "DELETE FROM `event` WHERE ( `id` = ? )" with ParamValues: 0='1'] at /notitia/local/lib/App/Notitia/Model/Event.pm line 234 

There should be a chained delete to remove participants, owners etc and allow the event to be deleted without having to find and un-participate everyone individually first. Problem here seems to be that where a vehicle request has been revised such that no vehicles are needed, the record in vehicle_requests remains and prevents deletion of the parent event record.

I think ON DELETE CASCADE is missing from
 CONSTRAINT `vehicle_request_fk_event_id` FOREIGN KEY (`event_id`) REFERENCES `event` (`id`)

in the vehicle_request table

**Comment by pjfl** [comment] 2016-04-03 11:58
I'm going to call this a bug, either it should delete the parent rows or it should stop winging about it,
in which case this is a duplicate of #13

**Comment by pjfl** [comment] 2016-04-03 14:22
I've added the missing has_many vehicle_requests relationship to the Event class. This should cause
the expected cascade delete to take place. Will retest when the schema change makes it into the wild

**Closed** 2016-04-03 16:25 UTC
Labels: bug
