### ISSUE TITLE
Can't delete a user

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#21] opened 2016-04-02 22:32 UTC
Try to delete a user that is assigned to a slot and you get

DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Cannot delete or update a parent row: a foreign key constraint fails (`schedule`.`slot`, CONSTRAINT `slot_fk_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `person` (`id`)) [for Statement "DELETE FROM `person` WHERE ( `id` = ? )" with ParamValues: 0='3'] at /notitia/local/lib/App/Notitia/Model/Admin.pm line 380

it would be much better if either delete was disabled in this case, or cascade-deletes were implemented 
 Is CASCADE DELETE missing from

CONSTRAINT `event_fk_owner_id` FOREIGN KEY (`owner_id`) REFERENCES `person` (`id`)

**Comment by pjfl** [comment] 2016-04-03 11:57
I'm going to call this a bug, either it should delete the parent rows or it should stop winging about it,
in which case this is a duplicate of #13

**Comment by pjfl** [comment] 2016-04-03 14:31
I've added the missing has_many slots relationship to the Person class. This should cause
the expected cascade delete to take place. Will retest when the schema change makes it into the wild

**Closed** 2016-04-03 16:24 UTC
Labels: bug
